//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task7 {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Task7.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Method whith anonym delegate as filter condition.
        /// </summary>
        internal static string Anonym {
            get {
                return ResourceManager.GetString("Anonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Method whith delegate as filter condition.
        /// </summary>
        internal static string Delegate {
            get {
                return ResourceManager.GetString("Delegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find all positive test methods, test array length: .
        /// </summary>
        internal static string FindPositiveTest {
            get {
                return ResourceManager.GetString("FindPositiveTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please input something to test:.
        /// </summary>
        internal static string InputPositiveInteger {
            get {
                return ResourceManager.GetString("InputPositiveInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Method whith lambda delegate as filter condition.
        /// </summary>
        internal static string Lambda {
            get {
                return ResourceManager.GetString("Lambda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LINQ.
        /// </summary>
        internal static string LINQ {
            get {
                return ResourceManager.GetString("LINQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Simple method.
        /// </summary>
        internal static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If you willing to repeat please input &quot;{0}&quot; or anything else to exit: .
        /// </summary>
        internal static string RepeatMessage {
            get {
                return ResourceManager.GetString("RepeatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Array sum.
        /// </summary>
        internal static string SubTask1Descr {
            get {
                return ResourceManager.GetString("SubTask1Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is input, a positive integer.
        /// </summary>
        internal static string SubTask2Descr {
            get {
                return ResourceManager.GetString("SubTask2Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test of finding methods.
        /// </summary>
        internal static string SubTask3Descr {
            get {
                return ResourceManager.GetString("SubTask3Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Task7. Extensions and LINQ.
        /// </summary>
        internal static string Task7 {
            get {
                return ResourceManager.GetString("Task7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To continue please input task number: .
        /// </summary>
        internal static string ToContinue {
            get {
                return ResourceManager.GetString("ToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorect input.
        /// </summary>
        internal static string WrongInput {
            get {
                return ResourceManager.GetString("WrongInput", resourceCulture);
            }
        }
    }
}